version: '2.2'
services:
  dev-db:
    image: postgres:14.5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - my_network
networks:
  my_network:
